#! C:\Python\Python36\python3

# 电脑随机出一个数字,用户输入进行猜测
# 1 定义变量接受电脑的数字
# 2 当用户输入的数字不对的时候,一直让用户输入
# 3 输入对的时候退出循环
import random
while True:
    computer_num = random.randint(0,999)

    player_num = int(input("I'm thinking of a number!"
                           "Try to guess the number"
                           "I'm thinking of:"))

    while computer_num != player_num:

        if player_num < computer_num:
            player_num = int(input("Too low! Guess again: "))
        elif player_num > computer_num:
            player_num = int(input("Too high! Guess again: "))

    player_act = input("That's it! Would you like to play again?(yes/no)")
    if player_act == "yes":
        # 当用户输入 yes 继续整个循环
        continue
    else:
        break
